name: sanbox-test

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-kernel:
    runs-on: self-hosted
    #ubuntu-latest
    steps:
      #- name: Configure git
      #  run: |
      #    git config --global --add safe.directory '*'
      - name: Checkout git
        run: |
          sudo apt-get install -y libelf-dev
          mkdir -p linux
          cd linux
          git init
          # PL
          git remote add origin https://git.kernel.org/pub/scm/linux/kernel/git/song/md.git
          git fetch origin --depth=5 36a5c03f232719eb4e2d925f4d584e09cfaf372c
          git reset --hard 36a5c03f232719eb4e2d925f4d584e09cfaf372c
          #git remote add origin https://github.com/${{ github.repository }}
          #git fetch origin --depth=5 ${{ github.event.pull_request.head.sha }}
          #git reset --hard ${{ github.event.pull_request.head.sha }}
          git log -1
      - name: Build kernel
        run: |
          cd linux
          make defconfig
          make -j 8
