name: sanbox-test

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
      - name: Checkout git
        run: |
          sudo apt-get install -y libelf-dev
          mkdir -p linux
          cd linux
          git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/song/md.git
          #git remote add origin https://github.com/${{ github.repository }}
          #git fetch origin --depth=5 ${{ github.event.pull_request.head.sha }}
          #git reset --hard ${{ github.event.pull_request.head.sha }}
          git log -1
      - name: Build kernel
        run: |
          cd linux
          make defconfig
          make -j 8
