name: Build Linux Kernel in VM

# This workflow runs on a self-hosted runner with the "linux" label
on:
  push:
    branches: [ main ]
#  schedule:
 #   - cron: '0 0 * * *'  # Run every day at midnight (adjust as needed)

jobs:
  build:
    runs-on: local  # Specify self-hosted runner with "linux" label
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Test VM SSH
        run: |
          echo $PWD
          vagrant up
          vagrant ssh -c "ls -al"
          #ssh -o StrictHostKeyChecking=no vagrant@vm_ip "command_to_run_in_vm"
      
      #- name: Build IT
      #  run: |
      #    echo $PWD
      #    cd linux
      #    git pull
      #    make defconfig  # Choose a kernel config (adjust as needed)
      #    make -j$(nproc)  # Build using parallel jobs based on available CPUs

      #- name: Upload kernel image (optional)
      #  uses: actions/upload-artifact@v3  # Upload artifacts produced in the VM
      #  with:
      #    name: kernel-image
      #    path: /path/to/kernel/image/in/vm  # Path to the built kernel image within the VM

# Customize this workflow as needed:
#  * Adjust triggers (push events, schedules)
#  * Modify VM configuration (memory, CPUs, image)
#  * Install specific kernel build dependencies
#  * Choose a kernel configuration (defconfig)
#  * Specify the path to the built kernel image for upload
#  * Add additional steps for post-build actions (e.g., testing)

