name: Build Linux Kernel in VM

# This workflow runs on a self-hosted runner with the "linux" label
on:
  push:
    branches: [ main ]
#  schedule:
 #   - cron: '0 0 * * *'  # Run every day at midnight (adjust as needed)

jobs:
  build:
    runs-on: local  # Specify self-hosted runner with "linux" label
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Bring up VM
        run: |
          vagrant up
          vagrant ssh -c "pwd && ls -al"
      
      - name: Update git repo
        run: |
          vagrant ssh -c "echo $PWD"
          vagrant ssh -c "cd linux && git pull"

      - name: Build the kernel
        run: |
          vagrant ssh -c "cd linux && make clean -j$(nproc)"
          vagrant ssh -c "cd linux && make defconfig"
          vagrant ssh -c "cd linux && make -j$(nproc)"

      #- name: Upload kernel image (optional)
      #  uses: actions/upload-artifact@v3  # Upload artifacts produced in the VM
      #  with:
      #    name: kernel-image
      #    path: /path/to/kernel/image/in/vm  # Path to the built kernel image within the VM

# Customize this workflow as needed:
#  * Adjust triggers (push events, schedules)
#  * Modify VM configuration (memory, CPUs, image)
#  * Install specific kernel build dependencies
#  * Choose a kernel configuration (defconfig)
#  * Specify the path to the built kernel image for upload
#  * Add additional steps for post-build actions (e.g., testing)

