name: Build Linux Kernel in VM

# This workflow runs on a self-hosted runner with the "linux" label
on:
  push:
    branches: [ main ]
#  schedule:
 #   - cron: '0 0 * * *'  # Run every day at midnight (adjust as needed)

jobs:
  build:
    runs-on: self-hosted  # Specify self-hosted runner with "linux" label
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Bring up VM
        run: |
          cd /home/ci/vagrant
          vagrant up
          vagrant ssh -c "pwd && ls -al"
      
      - name: Update git repo
        run: |
          cd /home/ci/vagrant
          vagrant ssh -c "echo $PWD"
          #vagrant ssh -c "cd linux" # && git pull"

      - name: Build and install kernel, reboot
        id: build
        run: |
          cd /home/ci/vagrant
          vagrant ssh -c "cd md && make clean -j$(nproc)"
          vagrant ssh -c "cd md && make defconfig"
          vagrant ssh -c "cd md && make bzImage -j$(nproc)"
          vagrant ssh -c "cd md && make modules -j$(nproc)"
          vagrant ssh -c "cd md && sudo make modules_install -j$(nproc)"
          vagrant ssh -c "cd md && sudo make install -j$(nproc)"
          #vagrant ssh -c "gcc hello.c"
          if: build.outputs.num == 0
            run: echo build.outputs.num == 0
          
          #vagrant ssh -c "./a.out"
                    
          vagrant halt

      - name: Bring up VM after reboot
        run: |
           cd /home/ci/vagrant
           vagrant up
           vagrant ssh -c "uname -r"

