name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]
    
env:
    JOB_OUT: "output.txt"
     
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Get user's e-mail
        run: |
          echo "MAIL_ATTACH=$JOB_OUT" >> $GITHUB_ENV 
          echo "Pull Request Info:" > $JOB_OUT
          echo "Author: ${{ github.event.pull_request.user.login }}" >> $JOB_OUT
          echo "Title: ${{ github.event.pull_request.title }}" >> $JOB_OUT
          echo "Body: ${{ github.event.pull_request.body }}" >> $JOB_OUT
          echo "USER_EMAIL=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV 
          # for now add the sender email to the SUBJECT as I'm sending to myself while debugging
          echo "SUBJECT=Github Actions job FAILURE for $(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV
        # TODO:  remove next line, here for testing only as push of yaml won't work without it
        continue-on-error: true 
      - name: Filter mis-routed mdadm patches
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"mdadm"* ]]; then
            echo "MDADM='Patch likely meant for mdadm repo, aborting'" >> $GITHUB_ENV
            exit 1
          fi
      - name: Build the project
        id: build
        run: |
          make > out.txt 2>&1
          echo "Build SUCCESS"
          cat out.txt
      - name: Failure information
        if: failure()
        run: |
         if [[ -n "${{ env.MDADM }}" ]]; then
            echo "Job failures:" >> $JOB_OUT
            echo "${{ env.MDADM }}" >> $JOB_OUT
            echo "${{ env.MDADM }}"
         else
            echo "Build FAILURE" >> $JOB_OUT
            cat out.txt >> $JOB_OUT
            cat out.txt
         fi
         echo "Attach: ${{ env.MAIL_ATTACH }}"
         ls -al
         cat "${{ env.MAIL_ATTACH }}"
      - name: Send build fail mail
        if: failure()
        uses: peluse/action-send-mail@v1.2 # from dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSKEY }}
          subject: ${{ env.SUBJECT }} 
          to: paul.e.luse@intel.com
          #${{ env.USER_EMAIL }}
          from: md-raid-ci
          body: Build job of ${{ github.repository }} completed with failure! See attachments.
          attachments: ${{ env.MAIL_ATTACH }}
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "Build worked, no email sent"
