name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
    MAX_VAG_RETRIES: "3"
    VAG_RETRY_DELAY: "5"
    HOME_DIR: ${{ github.workspace }}"
    REPO_NAME: ${{ github.repository_name }}
      
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the project
        run: |
          pwd
          ls -al
          gcc hello.c
          ./a.out
          echo "This is some output:"
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
          echo "Now the other one:"
          cat  $GITHUB_OUTPUT      
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSKEY}}
          subject: Github Actions job result
          to: paul.e.luse@intel.com
          from: paul.e.luse@intel.com # <user@example.com>
          body: Build job of ${{github.repository}} completed successfully!
          reply_to: paul.e.luse@intel.com


          # Optional nodemailerlog: true/false
          #nodemailerlog: false
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          #nodemailerdebug: false
