name: sandbox-per-patch
# tested with v1 vagrant snapshot..

on:
  pull_request:
  push:
    branches: [ "main" ]
     
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the project
        run: |
          make > out.txt 2>&1
          echo "Build SUCCESS" 
          signed_off_by=$(git log -1 HEAD --format='%s' | grep -o 'Signed-off-by: .*')
          #echo "Signed-off-by: (git log -1 HEAD --format='%s' | grep -o 'Signed-off-by: .*')"

          cat out.txt
      #- name: Print GitHub context
      #  run: echo "$GITHUB_CONTEXT"
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Handle build failure
        if: failure()
        run: |
          echo "Build FAILED" 
          echo "${{github.event.pull_request.user.email}}"
          cat out.txt
      - name: Send build fail mail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSKEY}}
          subject: Github Actions job result FAIL
          to: ${{github.event.pull_request.user.email}}
          from: md-raid-ci
          body: Build job of ${{github.repository}} completed successfully!
          attachments: out.txt
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "Build worked, no email"

