name: sandbox-per-patch
# tested with v1 vagrant snapshot.

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
    MAX_VAG_RETRIES: "3"
    VAG_RETRY_DELAY: "5"
    HOME_DIR: ${{ github.workspace }}"
    REPO_NAME: ${{ github.repository_name }}
      
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the project
        run: |
          pwd
          ls -al
          make > out.txt 2>&1
        #continue-on-error: true
      - name: test stuff
        if: failure()
        run: |
          echo "Build FAILED" 
          cat out.txt
          #ecit 1
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSKEY}}
          subject: Github Actions job result 3
          to: paul.e.luse@intel.com
          from: md-raid-ci
          body: Build job of ${{github.repository}} completed successfully!
          attachments: out.txt
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "This is the end:"
          echo "${{steps.build.outputs.fail}}"
          if [[ "${{steps.build.outputs.fail}}" == "true" ]]; then
            exit 1
          fi

