name: VM-sanbox-test

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-kernel:
    runs-on: self-hosted
    steps:
      - name: VM login
        run: |
          cd /home/ci/vagrant
          vagrant up
          vagrant ssh 'uname -r'
          vagrant halt
          
      #- name: Checkout git
      #  run: |
      #    rm -rf linux
      #    mkdir -p linux
      #    cd linux
      #    git init
      #    # PL
      #    git remote add origin https://git.kernel.org/pub/scm/linux/kernel/git/song/md.git
      #    git fetch origin --depth=5 36a5c03f232719eb4e2d925f4d584e09cfaf372c
      #    git reset --hard 36a5c03f232719eb4e2d925f4d584e09cfaf372c
      #    git log -1
      #- name: Build kernel
      #  run: |
      #    cd linux
      #    make defconfig
      #    make bzImage -j32
      #    make modules -j32
      #    uname -r
      #- name: Reboot kernel
      #  run: |
      #    reboot
      #    uname -r
