name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]
     
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      #- uses: actions/checkout@v4
      #  with:
      #    fetch-depth: 0 #needed for next step to work
      - name: Checkout source
        run: |
          cd ..
          rm -rf sandtmp
          mkdir -p sandtmp
          cd sandtmp
          git init
          git config --global --add safe.directory '*'
          echo "add origin https://github.com/${{ github.repository }}"
          git remote add origin https://github.com/${{ github.repository }}
          echo "Fetching code..."
          git fetch origin --depth=1 ${{ github.event.pull_request.head.sha }}
          echo "Resetting head..."
          git reset --hard ${{ github.event.pull_request.head.sha }}
          echo "Ready to configure..."
      - name: Get user's e-mail
        run: |
          git checkout remotes/origin/${{ github.head_ref }}
          echo "USER_EMAIL=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV 
          echo "SUBJECT=Github Actions job FAILURE for $(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV
        # TODO:  remove next line, here for testing only as push of yaml won't work without iy
        continue-on-error: true 
      - name: Filter mis-routed mdadm patches
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"mdadm"* ]]; then
            echo "MDADM='Patch likely meant for mdadm repo, aborting'" >> $GITHUB_ENV
            exit 1
          fi
      - name: Build the project
        id: build
        run: |
          make > out.txt 2>&1
          echo "Build SUCCESS" 
          cat out.txt
      - name: Handle failure
        if: failure()
        run: |
         if [[ -n "${{ env.MDADM }}" ]]; then
            echo "${{ env.MDADM }}" > out.txt
         else
            echo "Build FAILURE"
         fi
         cat out.txt
      - name: Send build fail mail
        if: failure()
        uses: peluse/action-send-mail@v1.1 # xx dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSKEY}}
          subject: ${{ env.SUBJECT }} 
          #Github Actions job FAILURE
          to: paul.e.luse@intel.com
          #${{ env.USER_EMAIL }}
          from: md-raid-ci
          body: Build job of ${{github.repository}} completed with failure! See attachment.
          attachments: out.txt
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "Build worked, no email sent"
