name: sandbox-per-patch
# tested with v1 vagrant snapshot.

on:
  pull_request:
  push:
    branches: [ "main" ]
     
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the project
        id: build
        run: |
          make > out.txt 2>&1
          echo "Build SUCCESS" 
          cat out.txt
          echo "author=$(git log -1 HEAD | grep -m 1 -E -o '[[:alnum:]\._-]+@[[:alnum:]\._-]+\.[[:alnum:]]{2,}')" >> "$GITHUB_OUTPUT"
      - name: Handle build failure
        if: failure()
        run: |
          echo "Build FAILED" 
          cat out.txt
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: 20.13.1
      - name: Install Dependencies
        run: |
          npm install @actions/github
          npm install @actions/core
      - name: Send build fail mail
        #if: failure()
        uses: peluse/action-send-mail@v1.0 #dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSKEY}}
          subject: Github Actions job result FAIL
          to: paul.e.luse@intel.com
          #${{steps.build.outputs.author}}
          from: md-raid-ci
          body: Build job of ${{github.repository}} completed successfully!
          attachments: out.txt
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "Build worked, no email"

