name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]
    
env:
    BUILD_OUT: "build.txt"
    WRONG_REPO: "mdadm.txt"
    TEST1_FAIL: "test1.txt"
     
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Get user's e-mail
        run: |
          my_list=("apple" "banana" "orange")
          comma_separated_string=$(join -v 1 -o 1.1 ', ' "${my_list[@]}")
          echo "$comma_separated_string"
          echo "USER_EMAIL=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV 
          echo "SUBJECT=Github Actions job FAILURE for $(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV
        # TODO:  remove next line, here for testing only as push of yaml won't work without iy
        continue-on-error: true 
      - name: Filter mis-routed mdadm patches
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"mdadm"* ]]; then
            echo "MDADM='Patch likely meant for mdadm repo, aborting'" >> $GITHUB_ENV
            exit 1
          fi
      - name: Build the project
        id: build
        run: |
          make > $BUILD_OUT 2>&1
          echo "Build SUCCESS" 
          cat $BUILD_OUT
      - name: Handle failure
        if: failure()
        run: |
         if [[ -n "${{ env.MDADM }}" ]]; then
            echo "${{ env.MDADM }}" > $WRONG_REPO
            maiL_artifacts+=[$WRONG_REPO]
            cat $WRONG_REPO
         else
            echo "Build FAILURE"
            maiL_artifacts+=[$BUILD_OUT]
            cat $BUILD_OUT
         fi
         echo "matrix: ${{ matrix.maiL_artifacts }}"
         att_string=$(echo "${{ matrix.maiL_artifacts }}" | paste -sd ",")
         echo "ATTACHMENTS=$att_string" >> $GITHUB_ENV
         echo "$WRONG_REPO : $BUILD_OUT"
         echo "raw list: $maiL_artifacts"
         echo "string: $att_string"
         echo "expanded: $(echo '${{ matrix.maiL_artifacts }}' | paste -sd ',')"
         echo "the list: ${{ env.ATTACHMENTS }}"
      - name: Send build fail mail
        if: failure()
        uses: peluse/action-send-mail@v1.2 # xx dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSKEY }}
          subject: ${{ env.SUBJECT }} 
          #Github Actions job FAILURE
          to: paul.e.luse@intel.com
          #${{ env.USER_EMAIL }}
          from: md-raid-ci
          body: Build job of ${{ github.repository }} completed with failure! See attachment.
          attachments: ${{ env.ATTACHMENTS }} 
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "Build worked, no email sent"
