name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
    MAX_VAG_RETRIES: "3"
    VAG_RETRY_DELAY: "5"
    HOME_DIR: ${{ github.workspace }}"
    REPO_NAME: ${{ github.repository_name }}
    
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - name: ✨ Send email, you star
        uses: dawidd6/action-send-mail@v1.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: quadmx08
          password: ${{ secrets.GMAIL_PASS }}
          subject: Your a star ✨
          body: ${{ github.actor }} just starred your mail-on-star repo!!! ${{ github.repository }}
          to: ${{ secrets.GMAIL_ADDRESS }}
          from: ${{ secrets.GMAIL_ADDRESS }}
