name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
    MAX_VAG_RETRIES: "3"
    VAG_RETRY_DELAY: "5"
    HOME_DIR: ${{ github.workspace }}"
    REPO_NAME: ${{ github.repository_name }}
    
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - name: Do nothing
        run: |
          pwd
          ls -al
          echo "Under construction..."
      - uses: actions/send-mail@v3
        with:
          to: paul.e.luse@intel.com
          subject: Workflow Completed
          body: The workflow has successfully completed.
