name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]
     
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 #needed for next step to work
      - name: Get user's e-mail
        id: user_email
        run: |
          git checkout remotes/origin/${{ github.head_ref }}
          echo "USER_EMAIL=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV 
        continue-on-error: true
      - name: Filter mis-routed mdadm patches
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"mdadm"* ]]; then
            echo "Patch likely meant for mdadm repo, aborting"
            exit 1
          fi
        continue-on-error: false
      - name: Build the project
        id: build
        run: |
          make > out.txt 2>&1
          echo "Build SUCCESS" 
          cat out.txt
      - name: Handle build failure
        if: failure()
        run: |
          echo "Build FAILURE" 
          cat out.txt
      - name: Send build fail mail
        if: failure()
        uses: peluse/action-send-mail@v1.0 # xx dawidd6/action-send-mail@v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSKEY}}
          subject: Github Actions job FAILURE
          to: ${{ env.USER_EMAIL }}
          from: md-raid-ci
          body: Build job of ${{github.repository}} completed with failure! See attachment.
          attachments: out.txt
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "Build worked, no email sent"
