name: sandbox-per-patch
# tested with v1 vagrant snapshot...

on:
  pull_request:
  push:
    branches: [ "main" ]
     
jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 #needed for next step to work
      - name: Get user's e-mail
        id: user_email
        run: |
          git checkout remotes/origin/${{ github.head_ref }}
          echo "USER_EMAIL=$(git log -n 1 --pretty=format:%ae)" >> $GITHUB_ENV 
        continue-on-error: true
      - name: Filter mis-routed mdadm patches
        run: |
          echo "SUBJECT=$(${{ github.event.pull_request.title }})" >> $GITHUB_ENV 
          echo "here comes title... ${{ github.event.pull_request.title }}"
          echo "${{ env.SUBJECT }}"
           echo "here comes title..."
          if [[ "$SUBJECT" == *"mdadm"* ]]; then
            echo "String found"
            exit 0
          else
            echo "String not found"
          fi
      - name: Build the project
        id: build
        run: |
          make > out.txt 2>&1
          echo "Build SUCCESS" 
          cat out.txt
      - name: Handle build failure
        if: failure()
        run: |
          echo "Build FAILED" 
          cat out.txt
          #echo "USER_EMAIL=$(git show -s --pretty=%ae ${{ github.event.pull_request.head.sha }}))" >> $GITHUB_ENV 
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: 20.13.1
      #- name: Install Dependencies
      #  run: |
      #    npm install @actions/github
      #    npm install @actions/core
      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: my_artifact
      #    path: artifact.txt
      - name: Send build fail mail
        if: failure()
        uses: peluse/action-send-mail@v1.0 # xx dawidd6/action-send-mail@v3.12.0
        with:
          #github_token: ${{secrets.GITHUB_TOKEN}}
          server_address: smtp.gmail.com
          server_port: 465
          ignore_cert: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSKEY}}
          subject: Github Actions job FAILURE
          to: ${{ env.USER_EMAIL }}
          #paul.e.luse@intel.com
          #${{steps.build.outputs.author}}
          from: md-raid-ci
          body: Build job of ${{github.repository}} completed with failure! See attachment.
          attachments: out.txt
          reply_to: paul.e.luse@intel.com
      - name: final stuff
        run: |
          echo "Build worked, no email"
