name: VM-sandbox-test
# tested with v1 vagrant snapshot 
# TODO: create a working_dir var and start there every time, the relative paths
# used throughout here are hard to keep track of and not easy to maintain..

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  per-patch-testing:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: VM startup and check
        run: |
          echo "WHOMAI"
          whoami
          cd ..
          rm -rf linux
          echo "***************************"
          echo "Restoring clean VM image..."
          echo "***************************"
          ls run*
          vagrant snapshot restore clean_vm_v1
          MAX_RETRIES=3
          RETRY_DELAY=5
          for i in $(seq 1 $MAX_RETRIES); do
            echo "XXXXXXXXX"
            vagrant ssh -c "sudo sudo timedatectl set-timezone UTC && \
              sudo systemctl restart chronyd && sudo chronyc -a makestep && sleep 1"
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          done
          #vagrant ssh -c "sudo sudo timedatectl set-timezone UTC && \
          #  sudo systemctl restart chronyd && sudo chronyc -a makestep && sleep 1"
          MAX_RETRIES=3
          RETRY_DELAY=5
          for i in $(seq 1 $MAX_RETRIES); do
            echo "XXXXXXXXX"
            vagrant ssh -c "echo 'Fresh VM, hello world!' && date && uname -r && gcc --version"
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          done
          #vagrant ssh -c "echo 'Fresh VM, hello world!' && date && uname -r && gcc --version"
      - name: Checkout kernel source
        run: |
          cd ..
          echo "***********************"
          echo "Preparing Linux repo..."
          echo "***********************"
          sudo timedatectl set-timezone UTC
          sudo systemctl restart chronyd && sudo chronyc -a makestep && sleep 1
          mkdir -p linux
          cd linux
          git init
          git remote add origin https://git.kernel.org/pub/scm/linux/kernel/git/song/md.git
          # just a random hash for quick repo population, get this from PR
          echo "Fetching code..."
          git fetch origin --depth=5 36a5c03f232719eb4e2d925f4d584e09cfaf372c
          echo "Fetch Done, resetting..."
          git reset --hard 36a5c03f232719eb4e2d925f4d584e09cfaf372c
          echo "Ready to configure..."
      - name: Configure kernel
        run: |
          cd ..
          cp config.sh linux
          echo "********************************"
          echo "Prepare minimal kernel config..."
          echo "********************************"
          # Just testing this rety mechanism...
          MAX_RETRIES=3
          RETRY_DELAY=5
          for i in $(seq 1 $MAX_RETRIES); do
            vagrant ssh -c "cd host/linux && ./config.sh"
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          done
          #vagrant ssh -c "cd host/linux && ./config.sh"
      - name: Build kernel
        run: |
          cd ../linux
          echo "******************************"
          echo "Compile Linux on bare metal..."
          echo "******************************"
          make bzImage -j20
          make modules -j20
      - name: Install kernel
        run: |
          cd ..
          echo "***********************"
          echo "Install kernel in VM..."
          echo "***********************"
          vagrant up
          MAX_RETRIES=3
          RETRY_DELAY=5
          for i in $(seq 1 $MAX_RETRIES); do
            vagrant ssh -c "cd host/linux && sudo make modules_install -j20 && \
              sudo make install -j20"
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          done
          #vagrant ssh -c "cd host/linux && sudo make modules_install -j20 && \
          #  sudo make install -j20"
          # our VM clean image only has one index (0) so 1 is always correct
          MAX_RETRIES=3
          RETRY_DELAY=5
          for i in $(seq 1 $MAX_RETRIES); do
            vagrant ssh -c "sudo grubby --set-default-index=1 && sudo grubby --info ALL"
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          done
          #vagrant ssh -c "sudo grubby --set-default-index=1 && sudo grubby --info ALL"
      - name: VM reboot and version check
        run: |
          echo "***************************************"
          echo 'Reboot done, fire up VM and check uname'
          echo "***************************************"
          vagrant reload
          MAX_RETRIES=3
          RETRY_DELAY=5
          for i in $(seq 1 $MAX_RETRIES); do
            vagrant ssh -c "echo 'Reboot done, hello world!' && uname -r"
            if [ $? -eq 0 ]; then
              break
            fi
            echo "Vagrant SSH command failed. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          done
          #vagrant ssh -c "echo 'Reboot done, hello world!' && uname -r"
          #vagrant ssh -c 'uname -r'
      - name: Execute tests
        run: |
          echo "Under construction..."
      - name: All done, cleanup
        run: |          
          cd ..
          echo "Cleaning up..."
          # TODO: add testing cleanup
          vagrant halt
          rm -rf linux
